根据数据本身的波动性和相关性进行赋权

波动性即对比强度，用标准差表示，标准差越大，波动性越强，权重越高

相关性即冲突性，用相关系数表示，如果指标间的相关系数越大，冲突性越小，权重越低 为1-相关系数

计算时，对比强度1与冲突性指标进行相乘，并归一化处理，得到最终权重

In [55]:
import numpy as np

def CRITIC(df):
    std_d = np.std(df, axis=0)  # 对比强度
    mean_d = np.mean(df, axis=0)  # 均值
    cor_d = np.corrcoef(df.T)  # 相关系数矩阵
    # 将对角线元素设为0
    np.fill_diagonal(cor_d, 0)
    # 计算非对角线元素的互补值之和
    w_j = (1 - cor_d).sum(axis=0) * std_d
    return w_j
a = np.array([[9,10,175,100],
 [8,7,167,90],
 [6,3,154,70]], dtype=float)
print(a)
#进行规约,min-max规约能够进行很好的无量纲化处理，如果这个指标是越大越好
# 最小-最大归一化
for i in range(a.shape[1]):
    min_val = min(a[:, i])
    max_val = max(a[:, i])
    a[:, i] = (a[:, i] - min_val) / (max_val - min_val)
print(a)
weights = CRITIC(a)
print(weights)

[[  9.  10. 175. 100.]
 [  8.   7. 167.  90.]
 [  6.   3. 154.  70.]]
[[1.         1.         1.         1.        ]
 [0.66666667 0.57142857 0.61904762 0.66666667]
 [0.         0.         0.         0.        ]]
[0.4187497  0.41499726 0.41387517 0.4187497 ]


In [51]:
import numpy as np

def CRITIC(df):
    std_d = np.std(df, axis=0)  # 对比强度
    mean_d = np.mean(df, axis=0)  # 均值
    cor_d = np.corrcoef(df.T)  # 相关系数矩阵
    print("Correlation Matrix before setting diagonal to 0:\n", cor_d)
    # 将对角线元素设为0
    np.fill_diagonal(cor_d, 0)
    print("Correlation Matrix after setting diagonal to 0:\n", cor_d)
    # 计算非对角线元素的互补值之和
    w_j = (1 - cor_d).sum(axis=0) * std_d
    return w_j

a = np.array([
    [9, 10, 175, 100],
    [8, 7, 167, 90],
    [6, 3, 154, 70]
], dtype=float)  # 确保数据类型为浮点数
print("Original Data:\n", a)

# 进行规约, min-max规约能够进行很好的无量纲化处理，如果这个指标是越大越好
# 最小-最大归一化
for i in range(a.shape[1]):
    min_val = np.min(a[:, i])
    max_val = np.max(a[:, i])
    if max_val - min_val != 0:  # 防止除以零
        a[:, i] = (a[:, i] - min_val) / (max_val - min_val)
    else:
        a[:, i] = 0  # 如果最大值和最小值相同，则归一化后结果设为0

print("Normalized Data:\n", a)

weights = CRITIC(a)
print("Weights:\n", weights)


Original Data:
 [[  9.  10. 175. 100.]
 [  8.   7. 167.  90.]
 [  6.   3. 154.  70.]]
Normalized Data:
 [[1.         1.         1.         1.        ]
 [0.66666667 0.57142857 0.61904762 0.66666667]
 [0.         0.         0.         0.        ]]
Correlation Matrix before setting diagonal to 0:
 [[1.         0.99419163 0.99856828 1.        ]
 [0.99419163 1.         0.99852526 0.99419163]
 [0.99856828 0.99852526 1.         0.99856828]
 [1.         0.99419163 0.99856828 1.        ]]
Correlation Matrix after setting diagonal to 0:
 [[0.         0.99419163 0.99856828 1.        ]
 [0.99419163 0.         0.99852526 0.99419163]
 [0.99856828 0.99852526 0.         0.99856828]
 [1.         0.99419163 0.99856828 0.        ]]
Weights:
 [0.4187497  0.41499726 0.41387517 0.4187497 ]
